# Generated by Django 4.1.2 on 2022-10-24 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_alter_shippingaddress_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shippingaddress",
            options={"verbose_name_plural": "shipping addresses"},
        ),
    ]
